/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.login.frame;

import controller.Decode;
import static config.JDBCConnection.getJDBCConnection;
import constand.MySQLConstand;
import java.awt.Color;
import java.awt.Frame;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.BorderFactory;
import javax.swing.JTextField;
import model.user.Account;
import model.user.User;
import view.manager.ManagerFrame;
import view.other.NofiDialog;
import view.user.UserFrame;

/**
 *
 * @author Administrator
 */
public class LoginFrame extends javax.swing.JFrame {

    /**
     * Creates new form LoginFrame
     */
    public LoginFrame() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Hệ thống quản lý sách thư viện");
        setVisible(true);
        keyListenner(tf_username);
        keyListenner(tf_password);
    }
    

    
    public User user = new User();
    public Account account = new Account();

    public void setUser(User user) {
        this.user = user;
    }

    public User getUser() {
        return user;
    }

    public void setAccount(Account account){
        this.account = account;
    }

    public Account getAccount(){
        return account;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tf_username = new javax.swing.JTextField();
        tf_password = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        myButton1 = new view.other.MyButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel4.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("Đăng nhập");
        jPanel4.add(jLabel2);
        jLabel2.setBounds(340, 120, 230, 37);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Tên đăng nhập");
        jPanel4.add(jLabel1);
        jLabel1.setBounds(120, 190, 140, 50);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Mật khẩu");
        jPanel4.add(jLabel3);
        jLabel3.setBounds(140, 270, 119, 50);

        tf_username.setBackground(new java.awt.Color(238, 230, 227));
        tf_username.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        tf_username.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, Color.BLACK));
        tf_username.setSelectionColor(new java.awt.Color(3, 155, 216));
        jPanel4.add(tf_username);
        tf_username.setBounds(300, 190, 257, 50);

        tf_password.setBackground(new java.awt.Color(238, 230, 227));
        tf_password.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        tf_password.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, Color.BLACK));
        tf_password.setSelectionColor(new java.awt.Color(3, 155, 216));
        jPanel4.add(tf_password);
        tf_password.setBounds(300, 280, 257, 50);

        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel4.add(jLabel5);
        jLabel5.setBounds(120, 380, 40, 40);

        myButton1.setBorder(null);
        myButton1.setText("Đăng nhập");
        myButton1.setBorderColor(new java.awt.Color(238, 230, 227));
        myButton1.setColor(new java.awt.Color(0, 204, 204));
        myButton1.setColorClick(new java.awt.Color(0, 102, 102));
        myButton1.setColorOver(new java.awt.Color(0, 153, 153));
        myButton1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        myButton1.setRadius(40);
        myButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(myButton1);
        myButton1.setBounds(520, 360, 110, 40);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("✖");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel6);
        jLabel6.setBounds(770, 0, 30, 30);

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("➖");
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel7);
        jLabel7.setBounds(740, 0, 30, 30);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/loginbackground.jpg"))); // NOI18N
        jPanel4.add(jLabel4);
        jLabel4.setBounds(0, 0, 800, 530);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 533, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void keyListenner(JTextField jtf) {
        jtf.addKeyListener(new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent e) {
                // neu keycode == 10 ~ enter
                if (e.getKeyCode() == 10) {
                    login();
                }
            }
        }); 
    }
    
    private void login(){
        try{
            checkAccount();
            Class.forName(MySQLConstand.CLASS_NAME);
            Connection conn = getJDBCConnection();
            Statement stm = conn.createStatement();

            String idUser = String.valueOf(account.getIdAccount());
            String role = account.getRole();

            String sql = "select * from user where idUser='" + idUser + "'";
            ResultSet rs = stm.executeQuery(sql);
            
            
            if(rs.next()){
                user.setAccount(account);
                user.setName(rs.getString("name"));
                user.setYearBirthday(Integer.parseInt(rs.getString("yearbirthday")));
                user.setPhoneNumber(rs.getString("phonenumber"));
                user.setIdCard(rs.getString("idcard"));
                if (user.getAccount().getRole().equals("manager")) {
                    new ManagerFrame(user).setVisible(true);
                } else {
                    new UserFrame(user).setVisible(true);
                }
                dispose();
            }
            conn.close();
        } catch(Exception e){
            System.out.println(e.getMessage());
        }
    }
    
    private void myButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton1ActionPerformed
        login();
    }//GEN-LAST:event_myButton1ActionPerformed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        this.setState(Frame.ICONIFIED);
    }//GEN-LAST:event_jLabel7MouseClicked
    
    public void checkAccount(){
        try {
            Class.forName(MySQLConstand.CLASS_NAME);
            Connection conn = getJDBCConnection();
            String username = tf_username.getText();
            String password = String.valueOf(tf_password.getPassword());
            String passwordDB= Decode.decodePassword(password);
            Statement stm = conn.createStatement();

            String sql = "select * from account where username='" + username + "' and password='" + passwordDB + "'";
            ResultSet rs = stm.executeQuery(sql);
            
            if (rs.next()) {
                String idUser = rs.getString("idUser");
                String role = rs.getString("role");
                String mail = rs.getString("mail");
                
                account.setIdAccount(Integer.parseInt(idUser));
                account.setRole(role);
                account.setMail(mail);
                account.setUsername(username);
                account.setPassword(password);
            }
            else{
                NofiDialog nd = new NofiDialog("Sai tên đăng nhập hoặc mật khẩu.");
            }
            conn.close();
            
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel4;
    private view.other.MyButton myButton1;
    private javax.swing.JPasswordField tf_password;
    private javax.swing.JTextField tf_username;
    // End of variables declaration//GEN-END:variables
}
