/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.manager.ticket.form;

import static config.JDBCConnection.getJDBCConnection;
import constand.MySQLConstand;
import controller.AccountController;
import controller.BookController;
import controller.TicketController;
import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Date;
import javax.swing.BorderFactory;
import model.book.Book;
import model.ticket.BorrowTicket;
import model.user.User;
import view.manager.ticket.CreateTicketFrame;
import view.other.NofiDialog;

/**
 *
 * @author Administrator
 */
public class BorrowTicketForm extends javax.swing.JPanel {

    private BorrowTicket borrowticket;
    private CreateTicketFrame ctf;
    TicketController ticketController = new TicketController();
    AccountController accountController = new AccountController();
    BookController bookController = new BookController();

    /**
     * Creates new form BorrowTicketEditForm
     */
    public BorrowTicketForm() {
        initComponents();
    }

    public BorrowTicketForm(BorrowTicket ticket, CreateTicketFrame ctf) {
        initComponents();
        this.ctf = ctf;
        this.borrowticket = ticket;
        if(ticket.getBook() != null){
            tf_idbook.setText(String.valueOf(ticket.getBook().getId()));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usermenu = new javax.swing.JPopupMenu();
        user1 = new javax.swing.JMenuItem();
        user2 = new javax.swing.JMenuItem();
        user3 = new javax.swing.JMenuItem();
        bookmenu = new javax.swing.JPopupMenu();
        book1 = new javax.swing.JMenuItem();
        book2 = new javax.swing.JMenuItem();
        book3 = new javax.swing.JMenuItem();
        jPanel3 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        tf_idbook = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        tf_iduser = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        myButton2 = new view.other.MyButton();
        myButton1 = new view.other.MyButton();

        usermenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        usermenu.setPreferredSize(new java.awt.Dimension(320, 150));

        user1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        user1.setText("jMenuItem1");
        user1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        user1.setPreferredSize(new java.awt.Dimension(320, 30));
        user1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user1ActionPerformed(evt);
            }
        });
        usermenu.add(user1);

        user2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        user2.setText("jMenuItem2");
        user2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        user2.setPreferredSize(new java.awt.Dimension(320, 30));
        user2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user2ActionPerformed(evt);
            }
        });
        usermenu.add(user2);

        user3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        user3.setText("jMenuItem3");
        user3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        user3.setPreferredSize(new java.awt.Dimension(320, 30));
        user3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user3ActionPerformed(evt);
            }
        });
        usermenu.add(user3);

        bookmenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bookmenu.setPreferredSize(new java.awt.Dimension(320, 150));

        book1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        book1.setText("book1");
        book1.setPreferredSize(new java.awt.Dimension(320, 30));
        book1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                book1ActionPerformed(evt);
            }
        });
        bookmenu.add(book1);

        book2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        book2.setText("jMenuItem2");
        book2.setPreferredSize(new java.awt.Dimension(320, 30));
        book2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                book2ActionPerformed(evt);
            }
        });
        bookmenu.add(book2);

        book3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        book3.setText("jMenuItem3");
        book3.setPreferredSize(new java.awt.Dimension(320, 30));
        book3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                book3ActionPerformed(evt);
            }
        });
        bookmenu.add(book3);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel3MousePressed(evt);
            }
        });

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel8MousePressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel3.setText("ID Sách");

        tf_idbook.setBackground(new java.awt.Color(250, 250, 250));
        tf_idbook.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tf_idbook.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, Color.BLACK));
        tf_idbook.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf_idbookFocusLost(evt);
            }
        });
        tf_idbook.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_idbookKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tf_idbook, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tf_idbook, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel9MousePressed(evt);
            }
        });

        tf_iduser.setBackground(new java.awt.Color(250, 250, 250));
        tf_iduser.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tf_iduser.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, Color.BLACK));
        tf_iduser.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf_iduserFocusLost(evt);
            }
        });
        tf_iduser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_iduserKeyReleased(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setText("ID người mượn");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(tf_iduser, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(173, 173, 173))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tf_iduser, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        myButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        myButton2.setText("Hủy");
        myButton2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        myButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton2ActionPerformed(evt);
            }
        });

        myButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        myButton1.setText("Đồng ý");
        myButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        myButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(myButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(myButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
            .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(myButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(myButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void myButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton1ActionPerformed
        int iduser = Integer.parseInt(tf_iduser.getText());
        int idBook = Integer.parseInt(tf_idbook.getText());
        Book book = BookController.getBookById(idBook);
        User user = AccountController.getUserById(iduser);
        if (user ==  null){
            NofiDialog nd = new NofiDialog("Vui lòng kiểm tra lại thông tin người dùng.");
        }
        else if (!user.getAccount().getRole().equals("user")) {
            NofiDialog nd = new NofiDialog("Quản lí không thể mượn sách.");
        } 
        else {
            if (book == null) {
                NofiDialog nd = new NofiDialog("Vui lòng kiểm tra lại thông tin sách.");
            } else {
                
                if (!book.getStatus().equals("Khả dụng")){
                    String str =  book.getStatus();
                    NofiDialog nd = new NofiDialog("Sách " + str+".");
                }
                else{
                try {
                    //int a= 0/0;
                    ticketController.addBorrowTicket("đã xử lý", iduser, idBook, new Date());
                    int currentid = TicketController.getCurrentIdTicket();
                    ticketController.addLendTicket("chưa xử lý", new Date(new Date().getTime() + 1209600000), currentid);
                    ctf.dispose();
                } catch (Exception e) {
                    NofiDialog nd = new NofiDialog("Vui lòng kiểm tra lại thông tin.");
                }
                }
            }
        }
    }//GEN-LAST:event_myButton1ActionPerformed

    private void myButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton2ActionPerformed
        this.ctf.dispose();
    }//GEN-LAST:event_myButton2ActionPerformed

    private void tf_iduserFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_iduserFocusLost
       usermenu.setVisible(false);
    }//GEN-LAST:event_tf_iduserFocusLost

    private void tf_iduserKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_iduserKeyReleased
        usermenu.setLocation(tf_iduser.getLocationOnScreen().x, tf_iduser.getLocationOnScreen().y+48);
        usermenu.setVisible(true);
        try{
            Class.forName(MySQLConstand.CLASS_NAME);
            Connection conn = getJDBCConnection();
            Statement st  = conn.createStatement();
            
            String search = tf_iduser.getText().trim();
            String tmpData[] = new String[3];
            String sql = "select * from user";
            sql = sql + " where idUser like '%"+search+"%' or name like '%"+search+"%' or phonenumber like '%"+search+"%'";
            
            ResultSet rs = st.executeQuery(sql);
            int i=0;
            while(rs.next()){
                String id = String.valueOf(rs.getInt("idUser"));
                String name = rs.getString("name");
                String phone = rs.getString("phonenumber");
                String tmp = id + " - " + name + " - " + phone;
                tmpData[i] = tmp;
                i++;
                if(i==3) break;
            }
            user1.setText(tmpData[0]);
            user2.setText(tmpData[1]);
            user3.setText(tmpData[2]);
            
            conn.close();
        }catch(Exception e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_tf_iduserKeyReleased
    
    public String getID(String tmp){
        String[] tmp1 = tmp.split(" - ");
        return tmp1[0];
    }
    
    private void user1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_user1ActionPerformed
        usermenu.setVisible(false);
        tf_iduser.setText(getID(user1.getText()));
    }//GEN-LAST:event_user1ActionPerformed

    private void user2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_user2ActionPerformed
        usermenu.setVisible(false);
        tf_iduser.setText(getID(user2.getText()));
    }//GEN-LAST:event_user2ActionPerformed

    private void user3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_user3ActionPerformed
        usermenu.setVisible(false);
        tf_iduser.setText(getID(user3.getText()));
    }//GEN-LAST:event_user3ActionPerformed

    private void jPanel8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel8MousePressed
        usermenu.setVisible(false);
        bookmenu.setVisible(false);
    }//GEN-LAST:event_jPanel8MousePressed

    private void jPanel9MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel9MousePressed
        usermenu.setVisible(false);
        bookmenu.setVisible(false);
    }//GEN-LAST:event_jPanel9MousePressed

    private void jPanel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MousePressed
        usermenu.setVisible(false);
        bookmenu.setVisible(false);
    }//GEN-LAST:event_jPanel3MousePressed

    private void book1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_book1ActionPerformed
        bookmenu.setVisible(false);
        tf_idbook.setText(getID(book1.getText()));
    }//GEN-LAST:event_book1ActionPerformed

    private void book2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_book2ActionPerformed
        bookmenu.setVisible(false);
        tf_idbook.setText(getID(book2.getText()));
    }//GEN-LAST:event_book2ActionPerformed

    private void book3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_book3ActionPerformed
        bookmenu.setVisible(false);
        tf_idbook.setText(getID(book3.getText()));
    }//GEN-LAST:event_book3ActionPerformed

    private void tf_idbookFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_idbookFocusLost
        bookmenu.setVisible(false);
    }//GEN-LAST:event_tf_idbookFocusLost

    private void tf_idbookKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_idbookKeyReleased
        bookmenu.setLocation(tf_idbook.getLocationOnScreen().x, tf_idbook.getLocationOnScreen().y+48);
        bookmenu.setVisible(true);
        try{
            Class.forName(MySQLConstand.CLASS_NAME);
            Connection conn = getJDBCConnection();
            Statement st  = conn.createStatement();
            
            String search = tf_idbook.getText().trim();
            String tmpData[] = new String[3];
            String sql = "select * from book";
            sql = sql + " where idBook like '%"+search+"%' or name like '%"+search+"%' or author like '%"+search+"%'";
            
            ResultSet rs = st.executeQuery(sql);
            int i=0;
            while(rs.next()){
                String id = String.valueOf(rs.getInt("idBook"));
                String name = rs.getString("name");
                String author = rs.getString("author");
                String tmp = id + " - " + name + " - " + author;
                tmpData[i] = tmp;
                i++;
                if(i==3) break;
            }
            book1.setText(tmpData[0]);
            book2.setText(tmpData[1]);
            book3.setText(tmpData[2]);
            
            conn.close();
        }catch(Exception e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_tf_idbookKeyReleased
        

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem book1;
    private javax.swing.JMenuItem book2;
    private javax.swing.JMenuItem book3;
    private javax.swing.JPopupMenu bookmenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private view.other.MyButton myButton1;
    private view.other.MyButton myButton2;
    private javax.swing.JTextField tf_idbook;
    private javax.swing.JTextField tf_iduser;
    private javax.swing.JMenuItem user1;
    private javax.swing.JMenuItem user2;
    private javax.swing.JMenuItem user3;
    private javax.swing.JPopupMenu usermenu;
    // End of variables declaration//GEN-END:variables
}
